# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - namcheck

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_bc16ad2db366496d9884df5ca08492b7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0c9e72843df248508527402a8b2e0248 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_bc16ad2db366496d9884df5ca08492b7 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'namcheck'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_afe80a9cbcf646fc85cc5e6f8472940a }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_bc16ad2db366496d9884df5ca08492b7 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'